export { default as Asset } from './svgComponents/Asset'
export { default as GenerateBill } from './svgComponents/GenerateBill'
export { default as Location } from './svgComponents/Location'
export { default as WaterDroplet } from './svgComponents/WaterDroplet'
export { default as WaterMeter } from './svgComponents/WaterMeter'